import{a as h,S as w,i}from"./assets/vendor-tnUJPedx.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))e(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const c of a.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&e(c)}).observe(document,{childList:!0,subtree:!0});function n(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function e(t){if(t.ep)return;t.ep=!0;const a=n(t);fetch(t.href,a)}})();const L="48862987-6323d91c4dec4b8453f0076b5",E="https://pixabay.com/api/";async function g(o,s=1,n=40){try{return(await h.get(E,{params:{key:L,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:n}})).data}catch(e){throw console.error("Error fetching images:",e),e}}const d=document.querySelector(".gallery");function u(o,s=!1){const n=o.map(e=>`
        <a href="${e.largeImageURL}" class="gallery-item">
            <img src="${e.webformatURL}" alt="${e.tags}" />
            <div class="image-info">
                <p><strong>Likes:</strong> ${e.likes}</p>
                <p><strong>Views:</strong> ${e.views}</p>
                <p><strong>Comments:</strong> ${e.comments}</p>
                <p><strong>Downloads:</strong> ${e.downloads}</p>
            </div>
        </a>
        
    `).join("");s?(d.insertAdjacentHTML("beforeend",n),p()):d.innerHTML=n}function b(){d.innerHTML=""}function p(){const o=document.querySelectorAll(".gallery-item");if(o.length>0){const s=o[0].getBoundingClientRect().height;window.scrollBy({top:s*40*2,behavior:"smooth"})}}const f=new w(".gallery a"),l={formElem:document.querySelector("#search-form"),galleryElem:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".load-more"),loaderElem:document.querySelector(".loader")},r={query:"",page:1,perPage:40,totalHits:0};l.formElem.addEventListener("submit",async o=>{o.preventDefault();const s=o.target.elements.searchQuery,n=s.value.trim();if(!n){i.error({title:"Error",message:"Please enter a search term!"});return}r.query=n,r.page=1,b(),m(),l.loadMoreBtn.style.display="none";try{const e=await g(r.query,r.page,r.perPage);r.totalHits=e.totalHits,e.hits.length===0?i.warning({title:"No results",message:"No images found. Try again!"}):(u(e.hits),f.refresh(),r.page*r.perPage<r.totalHits&&(l.loadMoreBtn.style.display="block"))}catch{i.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{y()}s.value=""});l.loadMoreBtn.addEventListener("click",async()=>{r.page+=1,m();try{const o=await g(r.query,r.page,r.perPage);u(o.hits,!0),f.refresh(),p(),r.page*r.perPage>=r.totalHits&&(l.loadMoreBtn.style.display="none",i.info({title:"End",message:"We're sorry, but you've reached the end of search results."}))}catch{i.error({title:"Error",message:"Something went wrong."})}finally{y()}});function m(){l.loaderElem.style.display="block"}function y(){l.loaderElem.style.display="none"}
//# sourceMappingURL=index.js.map
