import{a as p,S as h,i}from"./assets/vendor-tnUJPedx.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))e(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const d of n.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&e(d)}).observe(document,{childList:!0,subtree:!0});function l(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function e(t){if(t.ep)return;t.ep=!0;const n=l(t);fetch(t.href,n)}})();const L="48862987-6323d91c4dec4b8453f0076b5",b="https://pixabay.com/api/";async function g(a,o=1,l=40){try{return(await p.get(b,{params:{key:L,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:l}})).data}catch(e){throw console.error("Error fetching images:",e),e}}const c=document.querySelector(".gallery");let u;function m(a,o=!1){const l=a.map(e=>`
        <a href="${e.largeImageURL}" class="gallery-item">
            <img src="${e.webformatURL}" alt="${e.tags}" />
            <div class="image-info">
                <p><strong>Likes:</strong> ${e.likes}</p>
                <p><strong>Views:</strong> ${e.views}</p>
                <p><strong>Comments:</strong> ${e.comments}</p>
                <p><strong>Downloads:</strong> ${e.downloads}</p>
            </div>
        </a>
        
    `).join("");o?c.insertAdjacentHTML("beforeend",l):c.innerHTML=l,u?u.refresh():u=new h(".gallery a")}function w(){c.innerHTML=""}function E(){const a=c.firstElementChild;if(a){const{height:o}=a.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}}const s={formElem:document.querySelector("#search-form"),galleryElem:document.querySelector(".gallery"),btnLoadMore:document.createElement("button"),loaderElem:document.querySelector(".loader")};s.btnLoadMore.textContent="Load more";s.btnLoadMore.classList.add("load-more");s.btnLoadMore.style.display="none";s.galleryElem.after(s.btnLoadMore);const r={query:"",page:1,perPage:40,totalHits:0};s.formElem.addEventListener("submit",async a=>{a.preventDefault();const o=a.target.elements.searchQuery,l=o.value.trim();if(!l){i.error({title:"Error",message:"Please enter a search term!"});return}r.query=l,r.page=1,w(),s.btnLoadMore.style.display="none",f();try{const e=await g(r.query,r.page,r.perPage);r.totalHits=e.totalHits,e.hits.length===0?i.warning({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"}):(m(e.hits),r.totalHits>r.perPage&&(s.btnLoadMore.style.display="block"))}catch{i.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{y()}o.value=""});s.btnLoadMore.addEventListener("click",async()=>{r.page+=1,f();try{const a=await g(r.query,r.page,r.perPage);m(a.hits,!0),E();const o=Math.ceil(r.totalHits/r.perPage);r.page>=o&&(s.btnLoadMore.style.display="none",i.info({title:"Notice",message:"We're sorry, but you've reached the end of search results."}))}catch{i.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{y()}});function f(){s.loaderElem.style.display="block"}function y(){s.loaderElem.style.display="none"}
//# sourceMappingURL=index.js.map
