import{a as w,S as f,i}from"./assets/vendor-tnUJPedx.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))e(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const d of a.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&e(d)}).observe(document,{childList:!0,subtree:!0});function n(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function e(t){if(t.ep)return;t.ep=!0;const a=n(t);fetch(t.href,a)}})();const E="48862987-6323d91c4dec4b8453f0076b5",L="https://pixabay.com/api/";async function g(o,s=1,n=40){try{return(await w.get(L,{params:{key:E,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:n}})).data}catch(e){throw console.error("Error fetching images:",e),e}}const c=document.querySelector(".gallery");let u;function p(o,s=!1){const n=o.map(e=>`
        <a href="${e.largeImageURL}" class="gallery-item">
            <img src="${e.webformatURL}" alt="${e.tags}" />
            <div class="image-info">
                <p><strong>Likes:</strong> ${e.likes}</p>
                <p><strong>Views:</strong> ${e.views}</p>
                <p><strong>Comments:</strong> ${e.comments}</p>
                <p><strong>Downloads:</strong> ${e.downloads}</p>
            </div>
        </a>
        
    `).join("");s?c.insertAdjacentHTML("beforeend",n):c.innerHTML=n,u?u.refresh():u=new f(".gallery a")}function b(){c.innerHTML=""}function q(){const o=c.firstElementChild;if(o){const{height:s}=o.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}}const l={formElem:document.querySelector("#search-form"),galleryElem:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".load-more"),loaderElem:document.querySelector(".loader")},m=new f(".gallery a"),r={query:"",page:1,perPage:40,totalHits:0};l.formElem.addEventListener("submit",async o=>{o.preventDefault();const s=o.target.elements.searchQuery,n=s.value.trim();if(!n){i.error({title:"Error",message:"Please enter a search term!"});return}r.query=n,r.page=1,b(),y(),l.loadMoreBtn.style.display="none";try{const e=await g(r.query,r.page,r.perPage);r.totalHits=e.totalHits,e.hits.length===0?i.warning({title:"No results",message:"No images found. Try again!"}):(p(e.hits),m.refresh(),r.page*r.perPage<r.totalHits&&(l.loadMoreBtn.style.display="block"))}catch{i.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{h()}s.value=""});l.loadMoreBtn.addEventListener("click",async()=>{r.page+=1,y();try{const o=await g(r.query,r.page,r.perPage);p(o.hits),m.refresh(),q(),r.page*r.perPage>=r.totalHits&&(l.loadMoreBtn.style.display="none",i.info({title:"End",message:"We're sorry, but you've reached the end of search results."}))}catch{i.error({title:"Error",message:"Something went wrong."})}finally{h()}});function y(){l.loaderElem.style.display="block"}function h(){l.loaderElem.style.display="none"}
//# sourceMappingURL=index.js.map
